# Generated by Django 5.1.3 on 2025-05-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='1', max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
                ('module', models.CharField(max_length=255)),
                ('average', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Difficulties',
                'unique_together': {('user_id', 'module')},
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
