# Generated by Django 5.1.3 on 2025-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdifficulty_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdifficulty',
            name='adaptability',
            field=models.JSONField(default=list),
        ),
    ]
