# Generated by Django 5.1.3 on 2025-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'Java Script'), ('java', 'Java')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('short-answer', 'Short Answer'), ('coding', 'Coding')], max_length=50)),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_option', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('expected_answers', models.JSONField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
