# Generated by Django 5.1.3 on 2025-03-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingquestion',
            name='user_id',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
