# Generated by Django 5.1.3 on 2025-04-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_programmingquestion_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingquestion',
            name='allocated_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='exam_id',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='student_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='student_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'Java Script'), ('java', 'Java'), ('cpp', 'Cpp'), ('c', 'C'), ('php', 'PHP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='title',
            field=models.TextField(),
        ),
    ]
