# Generated by Django 5.1.3 on 2025-04-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_programmingquestion_allocated_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingquestion',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
