# Generated by Django 5.1.3 on 2025-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_programmingquestion_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingquestion',
            name='answer_feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
