# Generated by Django 5.1.3 on 2025-04-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(default='1', max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('total_marks', models.IntegerField(default=0)),
                ('student_marks', models.IntegerField(default=0)),
            ],
        ),
    ]
