# Generated by Django 5.1.3 on 2025-05-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
